### PR TITLE
This implementation handles errors in the API functions.

### PR DESCRIPTION
**Pull request by anirbanpaulcom**
### Description :
This PR implements enhance Error handling in API functions.

### CODE REVIEW

**Comment by devkiran** [comment]
@anirbanpaulcom Have you considered moving the `handleAndReturnErrorResponse` to the `withAdmin` method so that you don't have to add a `try catch` block in each API handler? What do you think?

**Comment by anirbanpaulcom** [comment]
> @anirbanpaulcom Have you considered moving the `handleAndReturnErrorResponse` to the `withAdmin` method so that you don't have to add a `try catch` block in each API handler? What do you think?

Yes @devkiran, is there any problem? Do i need to change anything?

**Comment by devkiran** [comment]
@anirbanpaulcom Let's move the error handling logic to `withAdmin`, so we don't have to repeat that on route level.

**Comment by anirbanpaulcom** [comment]
> @anirbanpaulcom Let's move the error handling logic to `withAdmin`, so we don't have to repeat that on route level.

@devkiran , Done. Anything else?

**Comment by devkiran** [comment]
Thanks for your contribution! I think these changes not necessary right now. I'm closing this PR.

**Comment by anirbanpaulcom** [comment]
> Thanks for your contribution! I think these changes not necessary right now. I'm closing this PR.

@devkiran, Please let me know if these changes are needed or not, Thank you.


Screenshot from 2024-04-24 16-51-37
Screenshot from 2024-04-24 16-51-54

**Pull request closed without merging**
