### PR TITLE
Using Docker for containerizing the turbo-repo

### LINKED ISSUE #378: Creating Dockerfile
Hi @steven-tey . Are you looking for a contribution for a dockerfile in dub to create the image.
Would love to add it.

Regards

### PR DESCRIPTION
**Pull request by captain-Akshay**
this PR fixes #378 and #25
to run the docker containers run the following code:-

`docker compose up`

> 
P.S. Sorry for the delay i was busy with few other thing

### CODE REVIEW

**Comment by captain-Akshay** [comment]
@steven-tey

**Comment by steven-tey** [comment]
Thanks for the PR @captain-Akshay! Will this work with the dependency on external services like Vercel, Tinybird, etc.? (as per the [Caveats](https://dub.co/docs/self-hosting#caveats) section)

**Comment by captain-Akshay** [comment]
@steven-tey I believe so

**Comment by nyxb** [comment]
does the PR work?

**Comment by jo-chemla** [comment]
Is there any reason for closing the PR before merging - other than lack of interest from dub-inc team? Thanks!

**Comment by captain-Akshay** [comment]
@jo-chemla No it was actually my second PR on the same issue but lack of communication and delay I choose to close it

**Comment by loewenmichael** [comment]
@steven-tey

**Comment by loewenmichael** [comment]
@steven-tey

**Comment by sanjaydotpro** [comment]
Any updates on this? This issue has been there since 3 years now.

Is the team not interested in offering easy deployment of dub?

**Comment by Debjyoti2004** [comment]
I want to work on that issue could you assign to me??

**Pull request closed without merging**
