### PR TITLE
Implement Dub CLI OAuth with PKCE Login

### PR DESCRIPTION
**Pull request by sujjeee**
Feature #1334

### Steps to Test Locally:

Create an OAuth2 Application in Dub:

- Navigate to the [OAuth Apps tab](https://app.dub.co/settings/oauth-apps) in your Dub workspace.
- Click **`Create OAuth App`**.
- Fill out the required fields to set up your OAuth2 application.

Enable PKCE:

- Make sure to turn on the PKCE option in your OAuth2 application settings.

 Update Client ID:

```javascript
const oauth2Client = new OAuth2Client({
  // TODO: add client id here
  clientId: "",
  authorizationEndpoint: "https://app.dub.co/oauth/authorize",
  tokenEndpoint: "https://api.dub.co/oauth/token",
});
```

That's it!

You can now test the OAuth2 flow locally by logging into the CLI.

### CODE REVIEW

**Comment by sujjeee** [comment]
@devkiran any suggestions to secure envs in cli??

**Comment by devkiran** [comment]
@sujjeee Thanks for this PR. The new auth flow looks good to me. Sharing some feedbacks below:

- Dub access token expires after 2 hour. So the CLI must handle this and refresh the access token if needed. Most of the OAuth 2.0 client handle this by default.
- Can we close the browse window after the successful authentication?
- Let's replace the port `4040` with `4587`.
- It is okay to remove `code_verifier` after successful authentication. We should create a new one, if the user want to re-authenticate.

**Comment by sujjeee** [comment]
@devkiran 
- [x] Refresh the access token
- [ ] Close the browse window
- [x] Update port
- [x] Remove code_verifier

I tried to close the browser window with the following script:

```javascript
 res.end('<script>window.close();</script>');
 ```

but this showing me a warning in the browser console `Scripts may close only the windows that were opened by it`

**Comment by devkiran** [comment]
@sujjeee You may leave the task "Close the browse window". I'll find some time today to review the PR.

**Comment by devkiran** [comment]
Can you confirm the token refresh is handled? I'm getting the following error `Unauthorized: Access token expired.`

**Comment by sujjeee** [comment]
@devkiran Replace `expires_at: expiresAt ? Date.now() + expiresAt * 1000 : null` with `expires_at: Date.now() + 120 * 1000` in `callback.ts` and `getConfig()`.

**Comment by devkiran** [comment]
@sujjeee I've fixed the token refreshing.

**Comment by sujjeee** [comment]
@devkiran Cool! Looking forward to seeing it in production.

**Review by steven-tey — APPROVED** [review]

**Review by devkiran — APPROVED** [review]

**Comment by steven-tey** [comment]
🤯 incredible work on this @sujjeee 👏

**Comment by steven-tey** [comment]
🤯 incredible work on this @sujjeee 👏

Just tested it and it works perfectly:

https://github.com/user-attachments/assets/92248307-c9e7-4aa6-87e0-71a7bfb3a5b1

**Pull request merged**
