### PR TITLE
fix: redirection to login page on cancelling of consent of oauth providers

### PR DESCRIPTION
**Pull request by garvitkhandelwal**
### Summary

Fixes [#1429](https://github.com/dubinc/dub/issues/1429)
This PR aims to fix the issue which is raised under #1429. To summarise the issue here, when a user selected any OAuth provider to log in but then cancels on the permission page, it was not getting redirected to the default login page. This issue was instead causing the redirection to be handled via the nextauth's default redirection mechanism since it was not able to find our own signin route. More details on the issue can be found in the issue link added above.

### Changes

Added a signIn route in the pages configuration of nextAuth options. 

### Screenshot/Video of the fix:

https://github.com/user-attachments/assets/45723130-0298-4229-a16d-4e821d7143c3

### References:
https://github.com/nextauthjs/next-auth/discussions/3682

### CODE REVIEW

**Review by 0xJaskeerat — COMMENTED** [review]
Hey @garvitkhandelwal 
Please update your branch , it is out-of-date with the base branch

**Comment by garvitkhandelwal** [comment]
> Hey @garvitkhandelwal Please update your branch , it is out-of-date with the base branch

Done

**Comment by garvitkhandelwal** [comment]
@steven-tey apologies for tagging but is there anything I need to do to get this PR reviewed? I'm unable to get other oss.gg issues assigned to myself until this one is resolved.

**Review by steven-tey — APPROVED** [review]

**Pull request merged**
